#!E:\Programming\Code\Python\music-player\virtenv\Scripts\python.exe
# EASY-INSTALL-SCRIPT: 'mutagen==1.25.1','moggsplit'
__requires__ = 'mutagen==1.25.1'
import pkg_resources
pkg_resources.run_script('mutagen==1.25.1', 'moggsplit')
